### ISSUE TITLE
[REFACTOR] 렌더링 최적화

### ISSUE THREAD

**Issue by Withlaw** [wanted-Team-7/pre-onboarding-10th-4-7#24]
## 📌 Feature Issues
1. 처음 화면 진입시 `<Main />` 재실행이 4번 일어납니다.
2. 인풋창에 검색어를 입력하면 이때도 `<Main />` 재실행이 4번 일어납니다.

 두 상황 모두 렌더링이 최대 2번 일어나는 것이 가장 최적인 것 같습니다.
1) 첫 페이지 로드 -> 렌더링 1회 -> 투두리스트 로드 -> 렌더링 2회
2) 인풋창에 텍스트 입력 -> 렌더링 1회 -> 검색 결과 로드 -> 렌더링 2회

## ✨ To-do

- [ ] 불필요한 state 제거
- [ ] useEffect 대체
- [ ] 메모이징 훅 사용

**Comment by leejy001** [comment]
렌더링이 발생한다는 것은 state가 변경되며 발생하는 경우가 있는데
main에 모든 state와 로직을 넣어놔서 그러지 않을까요?

**Comment by Withlaw** [comment]
main에 불필요한 리렌더링을 유발하는 요소가 없는데도 렌더링이 예상보다 많이 된다면 분리를 시키는게 맞는 것 같습니다.

**Comment by jeongdopark** [comment]
시도해 보겠습니다 -!
