### ISSUE TITLE
임의 값의 검색 결과에 대한 이슈

### ISSUE THREAD

**Issue by leejy001** [wanted-Team-7/pre-onboarding-10th-4-7#6]
## 📌 Feature Issues
아래와 같이 임의의 todo 배열이 저장되어있는 경우
![list](https://github.com/wanted-Team-7/pre-onboarding-10th-4-7/assets/49552804/cbf0f28b-07db-4c3e-9f4b-95d9bb621335)

"test"라는 단어를 검색하는 경우 아래와 같이 아무런 검색 결과도 나타나질 않습니다.
![result](https://github.com/wanted-Team-7/pre-onboarding-10th-4-7/assets/49552804/392fb0dd-4ac7-4038-8cbf-4ca627b2556f)
![what](https://github.com/wanted-Team-7/pre-onboarding-10th-4-7/assets/49552804/ebaaf601-2b42-428b-a8f9-83d305211969)

하지만 과제 리드미에 적혀있는 예제 단어인 "lorem"의 경우에는 검색 결과가 나옵니다.
![캡처](https://github.com/wanted-Team-7/pre-onboarding-10th-4-7/assets/49552804/143be1aa-e363-4e1b-b447-2b5697e46a4f)

## ✨ To-do
- [ ] 다른 팀원 분들도 똑같은 이슈가 발생하는지 체크해주시길 바랍니다.

**Comment by 1yoouoo** [comment]
네 알겠습니다~

**Comment by Withlaw** [comment]
네. hello 검색 결과값은 없네요. 근데 검색어 타이핑을 할 때 h, e  ... 순서대로 입력하면 여러 데이터가 내려오긴 합니다.

**Comment by leejy001** [comment]
아 해당 부분에 대해서 의문점을 해소했습니다.
예를들어 내가 공부하기를 입력했을 경우에 "열심히 공부하기, 수학 공부하기, 영어 공부하기..."와 같은 여러 할일 목록을 예시로 띄어주고 취사선택을 하는기능을 구현하는 것 같네요
이슈는 닫겠습니다.
